name: Tauri Release

on:
  push:
    tags:
      - 'v*.*.*' # مانند v1.0.0

jobs:
  release:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Release ${{ github.ref_name }}'
          includeUpdaterJson: true
          # Optional:
          # args: "--target x86_64-unknown-linux-gnu" # یا target خاص
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}